# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/12adi/Desktop/לימודים/תכנות מערכות 2/CPP_3"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/12adi/Desktop/לימודים/תכנות מערכות 2/CPP_3"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/12adi/Desktop/לימודים/תכנות מערכות 2/CPP_3/CMakeFiles" "/mnt/c/Users/12adi/Desktop/לימודים/תכנות מערכות 2/CPP_3//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/12adi/Desktop/לימודים/תכנות מערכות 2/CPP_3/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CoupGame

# Build rule for target.
CoupGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoupGame
.PHONY : CoupGame

# fast build rule for target.
CoupGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/build
.PHONY : CoupGame/fast

#=============================================================================
# Target rules for targets named TestGame

# Build rule for target.
TestGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGame
.PHONY : TestGame

# fast build rule for target.
TestGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/build
.PHONY : TestGame/fast

#=============================================================================
# Target rules for targets named CoupGame_autogen_timestamp_deps

# Build rule for target.
CoupGame_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoupGame_autogen_timestamp_deps
.PHONY : CoupGame_autogen_timestamp_deps

# fast build rule for target.
CoupGame_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame_autogen_timestamp_deps.dir/build.make CMakeFiles/CoupGame_autogen_timestamp_deps.dir/build
.PHONY : CoupGame_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named CoupGame_autogen

# Build rule for target.
CoupGame_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoupGame_autogen
.PHONY : CoupGame_autogen

# fast build rule for target.
CoupGame_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame_autogen.dir/build.make CMakeFiles/CoupGame_autogen.dir/build
.PHONY : CoupGame_autogen/fast

#=============================================================================
# Target rules for targets named TestGame_autogen_timestamp_deps

# Build rule for target.
TestGame_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGame_autogen_timestamp_deps
.PHONY : TestGame_autogen_timestamp_deps

# fast build rule for target.
TestGame_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame_autogen_timestamp_deps.dir/build.make CMakeFiles/TestGame_autogen_timestamp_deps.dir/build
.PHONY : TestGame_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named TestGame_autogen

# Build rule for target.
TestGame_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGame_autogen
.PHONY : TestGame_autogen

# fast build rule for target.
TestGame_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame_autogen.dir/build.make CMakeFiles/TestGame_autogen.dir/build
.PHONY : TestGame_autogen/fast

CoupGame_autogen/mocs_compilation.o: CoupGame_autogen/mocs_compilation.cpp.o
.PHONY : CoupGame_autogen/mocs_compilation.o

# target to build an object file
CoupGame_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/CoupGame_autogen/mocs_compilation.cpp.o
.PHONY : CoupGame_autogen/mocs_compilation.cpp.o

CoupGame_autogen/mocs_compilation.i: CoupGame_autogen/mocs_compilation.cpp.i
.PHONY : CoupGame_autogen/mocs_compilation.i

# target to preprocess a source file
CoupGame_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/CoupGame_autogen/mocs_compilation.cpp.i
.PHONY : CoupGame_autogen/mocs_compilation.cpp.i

CoupGame_autogen/mocs_compilation.s: CoupGame_autogen/mocs_compilation.cpp.s
.PHONY : CoupGame_autogen/mocs_compilation.s

# target to generate assembly for a file
CoupGame_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/CoupGame_autogen/mocs_compilation.cpp.s
.PHONY : CoupGame_autogen/mocs_compilation.cpp.s

GUI/AutoDemoWindow.o: GUI/AutoDemoWindow.cpp.o
.PHONY : GUI/AutoDemoWindow.o

# target to build an object file
GUI/AutoDemoWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoDemoWindow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoDemoWindow.cpp.o
.PHONY : GUI/AutoDemoWindow.cpp.o

GUI/AutoDemoWindow.i: GUI/AutoDemoWindow.cpp.i
.PHONY : GUI/AutoDemoWindow.i

# target to preprocess a source file
GUI/AutoDemoWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoDemoWindow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoDemoWindow.cpp.i
.PHONY : GUI/AutoDemoWindow.cpp.i

GUI/AutoDemoWindow.s: GUI/AutoDemoWindow.cpp.s
.PHONY : GUI/AutoDemoWindow.s

# target to generate assembly for a file
GUI/AutoDemoWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoDemoWindow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoDemoWindow.cpp.s
.PHONY : GUI/AutoDemoWindow.cpp.s

GUI/AutoGameWindow.o: GUI/AutoGameWindow.cpp.o
.PHONY : GUI/AutoGameWindow.o

# target to build an object file
GUI/AutoGameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoGameWindow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoGameWindow.cpp.o
.PHONY : GUI/AutoGameWindow.cpp.o

GUI/AutoGameWindow.i: GUI/AutoGameWindow.cpp.i
.PHONY : GUI/AutoGameWindow.i

# target to preprocess a source file
GUI/AutoGameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoGameWindow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoGameWindow.cpp.i
.PHONY : GUI/AutoGameWindow.cpp.i

GUI/AutoGameWindow.s: GUI/AutoGameWindow.cpp.s
.PHONY : GUI/AutoGameWindow.s

# target to generate assembly for a file
GUI/AutoGameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoGameWindow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoGameWindow.cpp.s
.PHONY : GUI/AutoGameWindow.cpp.s

GUI/AutoPlayerSetupWindow.o: GUI/AutoPlayerSetupWindow.cpp.o
.PHONY : GUI/AutoPlayerSetupWindow.o

# target to build an object file
GUI/AutoPlayerSetupWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoPlayerSetupWindow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoPlayerSetupWindow.cpp.o
.PHONY : GUI/AutoPlayerSetupWindow.cpp.o

GUI/AutoPlayerSetupWindow.i: GUI/AutoPlayerSetupWindow.cpp.i
.PHONY : GUI/AutoPlayerSetupWindow.i

# target to preprocess a source file
GUI/AutoPlayerSetupWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoPlayerSetupWindow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoPlayerSetupWindow.cpp.i
.PHONY : GUI/AutoPlayerSetupWindow.cpp.i

GUI/AutoPlayerSetupWindow.s: GUI/AutoPlayerSetupWindow.cpp.s
.PHONY : GUI/AutoPlayerSetupWindow.s

# target to generate assembly for a file
GUI/AutoPlayerSetupWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/AutoPlayerSetupWindow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/AutoPlayerSetupWindow.cpp.s
.PHONY : GUI/AutoPlayerSetupWindow.cpp.s

GUI/BlockingDialog.o: GUI/BlockingDialog.cpp.o
.PHONY : GUI/BlockingDialog.o

# target to build an object file
GUI/BlockingDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/BlockingDialog.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/BlockingDialog.cpp.o
.PHONY : GUI/BlockingDialog.cpp.o

GUI/BlockingDialog.i: GUI/BlockingDialog.cpp.i
.PHONY : GUI/BlockingDialog.i

# target to preprocess a source file
GUI/BlockingDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/BlockingDialog.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/BlockingDialog.cpp.i
.PHONY : GUI/BlockingDialog.cpp.i

GUI/BlockingDialog.s: GUI/BlockingDialog.cpp.s
.PHONY : GUI/BlockingDialog.s

# target to generate assembly for a file
GUI/BlockingDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/BlockingDialog.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/BlockingDialog.cpp.s
.PHONY : GUI/BlockingDialog.cpp.s

GUI/GameBoardWindow.o: GUI/GameBoardWindow.cpp.o
.PHONY : GUI/GameBoardWindow.o

# target to build an object file
GUI/GameBoardWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/GameBoardWindow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/GameBoardWindow.cpp.o
.PHONY : GUI/GameBoardWindow.cpp.o

GUI/GameBoardWindow.i: GUI/GameBoardWindow.cpp.i
.PHONY : GUI/GameBoardWindow.i

# target to preprocess a source file
GUI/GameBoardWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/GameBoardWindow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/GameBoardWindow.cpp.i
.PHONY : GUI/GameBoardWindow.cpp.i

GUI/GameBoardWindow.s: GUI/GameBoardWindow.cpp.s
.PHONY : GUI/GameBoardWindow.s

# target to generate assembly for a file
GUI/GameBoardWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/GameBoardWindow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/GameBoardWindow.cpp.s
.PHONY : GUI/GameBoardWindow.cpp.s

GUI/InstructionsWindow.o: GUI/InstructionsWindow.cpp.o
.PHONY : GUI/InstructionsWindow.o

# target to build an object file
GUI/InstructionsWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/InstructionsWindow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/InstructionsWindow.cpp.o
.PHONY : GUI/InstructionsWindow.cpp.o

GUI/InstructionsWindow.i: GUI/InstructionsWindow.cpp.i
.PHONY : GUI/InstructionsWindow.i

# target to preprocess a source file
GUI/InstructionsWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/InstructionsWindow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/InstructionsWindow.cpp.i
.PHONY : GUI/InstructionsWindow.cpp.i

GUI/InstructionsWindow.s: GUI/InstructionsWindow.cpp.s
.PHONY : GUI/InstructionsWindow.s

# target to generate assembly for a file
GUI/InstructionsWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/InstructionsWindow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/InstructionsWindow.cpp.s
.PHONY : GUI/InstructionsWindow.cpp.s

GUI/MainWindow.o: GUI/MainWindow.cpp.o
.PHONY : GUI/MainWindow.o

# target to build an object file
GUI/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/MainWindow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/MainWindow.cpp.o
.PHONY : GUI/MainWindow.cpp.o

GUI/MainWindow.i: GUI/MainWindow.cpp.i
.PHONY : GUI/MainWindow.i

# target to preprocess a source file
GUI/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/MainWindow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/MainWindow.cpp.i
.PHONY : GUI/MainWindow.cpp.i

GUI/MainWindow.s: GUI/MainWindow.cpp.s
.PHONY : GUI/MainWindow.s

# target to generate assembly for a file
GUI/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/MainWindow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/MainWindow.cpp.s
.PHONY : GUI/MainWindow.cpp.s

GUI/PlayerRegistrationScreen.o: GUI/PlayerRegistrationScreen.cpp.o
.PHONY : GUI/PlayerRegistrationScreen.o

# target to build an object file
GUI/PlayerRegistrationScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/PlayerRegistrationScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/PlayerRegistrationScreen.cpp.o
.PHONY : GUI/PlayerRegistrationScreen.cpp.o

GUI/PlayerRegistrationScreen.i: GUI/PlayerRegistrationScreen.cpp.i
.PHONY : GUI/PlayerRegistrationScreen.i

# target to preprocess a source file
GUI/PlayerRegistrationScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/PlayerRegistrationScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/PlayerRegistrationScreen.cpp.i
.PHONY : GUI/PlayerRegistrationScreen.cpp.i

GUI/PlayerRegistrationScreen.s: GUI/PlayerRegistrationScreen.cpp.s
.PHONY : GUI/PlayerRegistrationScreen.s

# target to generate assembly for a file
GUI/PlayerRegistrationScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/PlayerRegistrationScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/GUI/PlayerRegistrationScreen.cpp.s
.PHONY : GUI/PlayerRegistrationScreen.cpp.s

GUI/main.o: GUI/main.cpp.o
.PHONY : GUI/main.o

# target to build an object file
GUI/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/main.cpp.o
.PHONY : GUI/main.cpp.o

GUI/main.i: GUI/main.cpp.i
.PHONY : GUI/main.i

# target to preprocess a source file
GUI/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/main.cpp.i
.PHONY : GUI/main.cpp.i

GUI/main.s: GUI/main.cpp.s
.PHONY : GUI/main.s

# target to generate assembly for a file
GUI/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/GUI/main.cpp.s
.PHONY : GUI/main.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Game.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Game.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Game.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Game.cpp.s
.PHONY : Game.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Player.cpp.s
.PHONY : Player.cpp.s

Roles/Baron.o: Roles/Baron.cpp.o
.PHONY : Roles/Baron.o

# target to build an object file
Roles/Baron.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Baron.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Baron.cpp.o
.PHONY : Roles/Baron.cpp.o

Roles/Baron.i: Roles/Baron.cpp.i
.PHONY : Roles/Baron.i

# target to preprocess a source file
Roles/Baron.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Baron.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Baron.cpp.i
.PHONY : Roles/Baron.cpp.i

Roles/Baron.s: Roles/Baron.cpp.s
.PHONY : Roles/Baron.s

# target to generate assembly for a file
Roles/Baron.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Baron.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Baron.cpp.s
.PHONY : Roles/Baron.cpp.s

Roles/General.o: Roles/General.cpp.o
.PHONY : Roles/General.o

# target to build an object file
Roles/General.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/General.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/General.cpp.o
.PHONY : Roles/General.cpp.o

Roles/General.i: Roles/General.cpp.i
.PHONY : Roles/General.i

# target to preprocess a source file
Roles/General.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/General.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/General.cpp.i
.PHONY : Roles/General.cpp.i

Roles/General.s: Roles/General.cpp.s
.PHONY : Roles/General.s

# target to generate assembly for a file
Roles/General.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/General.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/General.cpp.s
.PHONY : Roles/General.cpp.s

Roles/Governor.o: Roles/Governor.cpp.o
.PHONY : Roles/Governor.o

# target to build an object file
Roles/Governor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Governor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Governor.cpp.o
.PHONY : Roles/Governor.cpp.o

Roles/Governor.i: Roles/Governor.cpp.i
.PHONY : Roles/Governor.i

# target to preprocess a source file
Roles/Governor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Governor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Governor.cpp.i
.PHONY : Roles/Governor.cpp.i

Roles/Governor.s: Roles/Governor.cpp.s
.PHONY : Roles/Governor.s

# target to generate assembly for a file
Roles/Governor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Governor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Governor.cpp.s
.PHONY : Roles/Governor.cpp.s

Roles/Judge.o: Roles/Judge.cpp.o
.PHONY : Roles/Judge.o

# target to build an object file
Roles/Judge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Judge.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Judge.cpp.o
.PHONY : Roles/Judge.cpp.o

Roles/Judge.i: Roles/Judge.cpp.i
.PHONY : Roles/Judge.i

# target to preprocess a source file
Roles/Judge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Judge.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Judge.cpp.i
.PHONY : Roles/Judge.cpp.i

Roles/Judge.s: Roles/Judge.cpp.s
.PHONY : Roles/Judge.s

# target to generate assembly for a file
Roles/Judge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Judge.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Judge.cpp.s
.PHONY : Roles/Judge.cpp.s

Roles/Merchant.o: Roles/Merchant.cpp.o
.PHONY : Roles/Merchant.o

# target to build an object file
Roles/Merchant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Merchant.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Merchant.cpp.o
.PHONY : Roles/Merchant.cpp.o

Roles/Merchant.i: Roles/Merchant.cpp.i
.PHONY : Roles/Merchant.i

# target to preprocess a source file
Roles/Merchant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Merchant.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Merchant.cpp.i
.PHONY : Roles/Merchant.cpp.i

Roles/Merchant.s: Roles/Merchant.cpp.s
.PHONY : Roles/Merchant.s

# target to generate assembly for a file
Roles/Merchant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Merchant.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Merchant.cpp.s
.PHONY : Roles/Merchant.cpp.s

Roles/RoleFactory.o: Roles/RoleFactory.cpp.o
.PHONY : Roles/RoleFactory.o

# target to build an object file
Roles/RoleFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/RoleFactory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/RoleFactory.cpp.o
.PHONY : Roles/RoleFactory.cpp.o

Roles/RoleFactory.i: Roles/RoleFactory.cpp.i
.PHONY : Roles/RoleFactory.i

# target to preprocess a source file
Roles/RoleFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/RoleFactory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/RoleFactory.cpp.i
.PHONY : Roles/RoleFactory.cpp.i

Roles/RoleFactory.s: Roles/RoleFactory.cpp.s
.PHONY : Roles/RoleFactory.s

# target to generate assembly for a file
Roles/RoleFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/RoleFactory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/RoleFactory.cpp.s
.PHONY : Roles/RoleFactory.cpp.s

Roles/Spy.o: Roles/Spy.cpp.o
.PHONY : Roles/Spy.o

# target to build an object file
Roles/Spy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Spy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Spy.cpp.o
.PHONY : Roles/Spy.cpp.o

Roles/Spy.i: Roles/Spy.cpp.i
.PHONY : Roles/Spy.i

# target to preprocess a source file
Roles/Spy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Spy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Spy.cpp.i
.PHONY : Roles/Spy.cpp.i

Roles/Spy.s: Roles/Spy.cpp.s
.PHONY : Roles/Spy.s

# target to generate assembly for a file
Roles/Spy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoupGame.dir/build.make CMakeFiles/CoupGame.dir/Roles/Spy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Roles/Spy.cpp.s
.PHONY : Roles/Spy.cpp.s

TestGame_autogen/mocs_compilation.o: TestGame_autogen/mocs_compilation.cpp.o
.PHONY : TestGame_autogen/mocs_compilation.o

# target to build an object file
TestGame_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/TestGame_autogen/mocs_compilation.cpp.o
.PHONY : TestGame_autogen/mocs_compilation.cpp.o

TestGame_autogen/mocs_compilation.i: TestGame_autogen/mocs_compilation.cpp.i
.PHONY : TestGame_autogen/mocs_compilation.i

# target to preprocess a source file
TestGame_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/TestGame_autogen/mocs_compilation.cpp.i
.PHONY : TestGame_autogen/mocs_compilation.cpp.i

TestGame_autogen/mocs_compilation.s: TestGame_autogen/mocs_compilation.cpp.s
.PHONY : TestGame_autogen/mocs_compilation.s

# target to generate assembly for a file
TestGame_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/TestGame_autogen/mocs_compilation.cpp.s
.PHONY : TestGame_autogen/mocs_compilation.cpp.s

Tests/Action_test.o: Tests/Action_test.cpp.o
.PHONY : Tests/Action_test.o

# target to build an object file
Tests/Action_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Action_test.cpp.o
.PHONY : Tests/Action_test.cpp.o

Tests/Action_test.i: Tests/Action_test.cpp.i
.PHONY : Tests/Action_test.i

# target to preprocess a source file
Tests/Action_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Action_test.cpp.i
.PHONY : Tests/Action_test.cpp.i

Tests/Action_test.s: Tests/Action_test.cpp.s
.PHONY : Tests/Action_test.s

# target to generate assembly for a file
Tests/Action_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Action_test.cpp.s
.PHONY : Tests/Action_test.cpp.s

Tests/Baron_test.o: Tests/Baron_test.cpp.o
.PHONY : Tests/Baron_test.o

# target to build an object file
Tests/Baron_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Baron_test.cpp.o
.PHONY : Tests/Baron_test.cpp.o

Tests/Baron_test.i: Tests/Baron_test.cpp.i
.PHONY : Tests/Baron_test.i

# target to preprocess a source file
Tests/Baron_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Baron_test.cpp.i
.PHONY : Tests/Baron_test.cpp.i

Tests/Baron_test.s: Tests/Baron_test.cpp.s
.PHONY : Tests/Baron_test.s

# target to generate assembly for a file
Tests/Baron_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Baron_test.cpp.s
.PHONY : Tests/Baron_test.cpp.s

Tests/EdgeCase_test.o: Tests/EdgeCase_test.cpp.o
.PHONY : Tests/EdgeCase_test.o

# target to build an object file
Tests/EdgeCase_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/EdgeCase_test.cpp.o
.PHONY : Tests/EdgeCase_test.cpp.o

Tests/EdgeCase_test.i: Tests/EdgeCase_test.cpp.i
.PHONY : Tests/EdgeCase_test.i

# target to preprocess a source file
Tests/EdgeCase_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/EdgeCase_test.cpp.i
.PHONY : Tests/EdgeCase_test.cpp.i

Tests/EdgeCase_test.s: Tests/EdgeCase_test.cpp.s
.PHONY : Tests/EdgeCase_test.s

# target to generate assembly for a file
Tests/EdgeCase_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/EdgeCase_test.cpp.s
.PHONY : Tests/EdgeCase_test.cpp.s

Tests/Game_test.o: Tests/Game_test.cpp.o
.PHONY : Tests/Game_test.o

# target to build an object file
Tests/Game_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Game_test.cpp.o
.PHONY : Tests/Game_test.cpp.o

Tests/Game_test.i: Tests/Game_test.cpp.i
.PHONY : Tests/Game_test.i

# target to preprocess a source file
Tests/Game_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Game_test.cpp.i
.PHONY : Tests/Game_test.cpp.i

Tests/Game_test.s: Tests/Game_test.cpp.s
.PHONY : Tests/Game_test.s

# target to generate assembly for a file
Tests/Game_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Game_test.cpp.s
.PHONY : Tests/Game_test.cpp.s

Tests/General_test.o: Tests/General_test.cpp.o
.PHONY : Tests/General_test.o

# target to build an object file
Tests/General_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/General_test.cpp.o
.PHONY : Tests/General_test.cpp.o

Tests/General_test.i: Tests/General_test.cpp.i
.PHONY : Tests/General_test.i

# target to preprocess a source file
Tests/General_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/General_test.cpp.i
.PHONY : Tests/General_test.cpp.i

Tests/General_test.s: Tests/General_test.cpp.s
.PHONY : Tests/General_test.s

# target to generate assembly for a file
Tests/General_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/General_test.cpp.s
.PHONY : Tests/General_test.cpp.s

Tests/Governor_test.o: Tests/Governor_test.cpp.o
.PHONY : Tests/Governor_test.o

# target to build an object file
Tests/Governor_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Governor_test.cpp.o
.PHONY : Tests/Governor_test.cpp.o

Tests/Governor_test.i: Tests/Governor_test.cpp.i
.PHONY : Tests/Governor_test.i

# target to preprocess a source file
Tests/Governor_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Governor_test.cpp.i
.PHONY : Tests/Governor_test.cpp.i

Tests/Governor_test.s: Tests/Governor_test.cpp.s
.PHONY : Tests/Governor_test.s

# target to generate assembly for a file
Tests/Governor_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Governor_test.cpp.s
.PHONY : Tests/Governor_test.cpp.s

Tests/Integration_test.o: Tests/Integration_test.cpp.o
.PHONY : Tests/Integration_test.o

# target to build an object file
Tests/Integration_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Integration_test.cpp.o
.PHONY : Tests/Integration_test.cpp.o

Tests/Integration_test.i: Tests/Integration_test.cpp.i
.PHONY : Tests/Integration_test.i

# target to preprocess a source file
Tests/Integration_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Integration_test.cpp.i
.PHONY : Tests/Integration_test.cpp.i

Tests/Integration_test.s: Tests/Integration_test.cpp.s
.PHONY : Tests/Integration_test.s

# target to generate assembly for a file
Tests/Integration_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Integration_test.cpp.s
.PHONY : Tests/Integration_test.cpp.s

Tests/Judge_test.o: Tests/Judge_test.cpp.o
.PHONY : Tests/Judge_test.o

# target to build an object file
Tests/Judge_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Judge_test.cpp.o
.PHONY : Tests/Judge_test.cpp.o

Tests/Judge_test.i: Tests/Judge_test.cpp.i
.PHONY : Tests/Judge_test.i

# target to preprocess a source file
Tests/Judge_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Judge_test.cpp.i
.PHONY : Tests/Judge_test.cpp.i

Tests/Judge_test.s: Tests/Judge_test.cpp.s
.PHONY : Tests/Judge_test.s

# target to generate assembly for a file
Tests/Judge_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Judge_test.cpp.s
.PHONY : Tests/Judge_test.cpp.s

Tests/Merchant_test.o: Tests/Merchant_test.cpp.o
.PHONY : Tests/Merchant_test.o

# target to build an object file
Tests/Merchant_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Merchant_test.cpp.o
.PHONY : Tests/Merchant_test.cpp.o

Tests/Merchant_test.i: Tests/Merchant_test.cpp.i
.PHONY : Tests/Merchant_test.i

# target to preprocess a source file
Tests/Merchant_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Merchant_test.cpp.i
.PHONY : Tests/Merchant_test.cpp.i

Tests/Merchant_test.s: Tests/Merchant_test.cpp.s
.PHONY : Tests/Merchant_test.s

# target to generate assembly for a file
Tests/Merchant_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Merchant_test.cpp.s
.PHONY : Tests/Merchant_test.cpp.s

Tests/Player_test.o: Tests/Player_test.cpp.o
.PHONY : Tests/Player_test.o

# target to build an object file
Tests/Player_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Player_test.cpp.o
.PHONY : Tests/Player_test.cpp.o

Tests/Player_test.i: Tests/Player_test.cpp.i
.PHONY : Tests/Player_test.i

# target to preprocess a source file
Tests/Player_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Player_test.cpp.i
.PHONY : Tests/Player_test.cpp.i

Tests/Player_test.s: Tests/Player_test.cpp.s
.PHONY : Tests/Player_test.s

# target to generate assembly for a file
Tests/Player_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Player_test.cpp.s
.PHONY : Tests/Player_test.cpp.s

Tests/Spy_test.o: Tests/Spy_test.cpp.o
.PHONY : Tests/Spy_test.o

# target to build an object file
Tests/Spy_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Spy_test.cpp.o
.PHONY : Tests/Spy_test.cpp.o

Tests/Spy_test.i: Tests/Spy_test.cpp.i
.PHONY : Tests/Spy_test.i

# target to preprocess a source file
Tests/Spy_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Spy_test.cpp.i
.PHONY : Tests/Spy_test.cpp.i

Tests/Spy_test.s: Tests/Spy_test.cpp.s
.PHONY : Tests/Spy_test.s

# target to generate assembly for a file
Tests/Spy_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/Tests/Spy_test.cpp.s
.PHONY : Tests/Spy_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... CoupGame_autogen"
	@echo "... CoupGame_autogen_timestamp_deps"
	@echo "... TestGame_autogen"
	@echo "... TestGame_autogen_timestamp_deps"
	@echo "... CoupGame"
	@echo "... TestGame"
	@echo "... CoupGame_autogen/mocs_compilation.o"
	@echo "... CoupGame_autogen/mocs_compilation.i"
	@echo "... CoupGame_autogen/mocs_compilation.s"
	@echo "... GUI/AutoDemoWindow.o"
	@echo "... GUI/AutoDemoWindow.i"
	@echo "... GUI/AutoDemoWindow.s"
	@echo "... GUI/AutoGameWindow.o"
	@echo "... GUI/AutoGameWindow.i"
	@echo "... GUI/AutoGameWindow.s"
	@echo "... GUI/AutoPlayerSetupWindow.o"
	@echo "... GUI/AutoPlayerSetupWindow.i"
	@echo "... GUI/AutoPlayerSetupWindow.s"
	@echo "... GUI/BlockingDialog.o"
	@echo "... GUI/BlockingDialog.i"
	@echo "... GUI/BlockingDialog.s"
	@echo "... GUI/GameBoardWindow.o"
	@echo "... GUI/GameBoardWindow.i"
	@echo "... GUI/GameBoardWindow.s"
	@echo "... GUI/InstructionsWindow.o"
	@echo "... GUI/InstructionsWindow.i"
	@echo "... GUI/InstructionsWindow.s"
	@echo "... GUI/MainWindow.o"
	@echo "... GUI/MainWindow.i"
	@echo "... GUI/MainWindow.s"
	@echo "... GUI/PlayerRegistrationScreen.o"
	@echo "... GUI/PlayerRegistrationScreen.i"
	@echo "... GUI/PlayerRegistrationScreen.s"
	@echo "... GUI/main.o"
	@echo "... GUI/main.i"
	@echo "... GUI/main.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Roles/Baron.o"
	@echo "... Roles/Baron.i"
	@echo "... Roles/Baron.s"
	@echo "... Roles/General.o"
	@echo "... Roles/General.i"
	@echo "... Roles/General.s"
	@echo "... Roles/Governor.o"
	@echo "... Roles/Governor.i"
	@echo "... Roles/Governor.s"
	@echo "... Roles/Judge.o"
	@echo "... Roles/Judge.i"
	@echo "... Roles/Judge.s"
	@echo "... Roles/Merchant.o"
	@echo "... Roles/Merchant.i"
	@echo "... Roles/Merchant.s"
	@echo "... Roles/RoleFactory.o"
	@echo "... Roles/RoleFactory.i"
	@echo "... Roles/RoleFactory.s"
	@echo "... Roles/Spy.o"
	@echo "... Roles/Spy.i"
	@echo "... Roles/Spy.s"
	@echo "... TestGame_autogen/mocs_compilation.o"
	@echo "... TestGame_autogen/mocs_compilation.i"
	@echo "... TestGame_autogen/mocs_compilation.s"
	@echo "... Tests/Action_test.o"
	@echo "... Tests/Action_test.i"
	@echo "... Tests/Action_test.s"
	@echo "... Tests/Baron_test.o"
	@echo "... Tests/Baron_test.i"
	@echo "... Tests/Baron_test.s"
	@echo "... Tests/EdgeCase_test.o"
	@echo "... Tests/EdgeCase_test.i"
	@echo "... Tests/EdgeCase_test.s"
	@echo "... Tests/Game_test.o"
	@echo "... Tests/Game_test.i"
	@echo "... Tests/Game_test.s"
	@echo "... Tests/General_test.o"
	@echo "... Tests/General_test.i"
	@echo "... Tests/General_test.s"
	@echo "... Tests/Governor_test.o"
	@echo "... Tests/Governor_test.i"
	@echo "... Tests/Governor_test.s"
	@echo "... Tests/Integration_test.o"
	@echo "... Tests/Integration_test.i"
	@echo "... Tests/Integration_test.s"
	@echo "... Tests/Judge_test.o"
	@echo "... Tests/Judge_test.i"
	@echo "... Tests/Judge_test.s"
	@echo "... Tests/Merchant_test.o"
	@echo "... Tests/Merchant_test.i"
	@echo "... Tests/Merchant_test.s"
	@echo "... Tests/Player_test.o"
	@echo "... Tests/Player_test.i"
	@echo "... Tests/Player_test.s"
	@echo "... Tests/Spy_test.o"
	@echo "... Tests/Spy_test.i"
	@echo "... Tests/Spy_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

